const fs = require('fs');
const path = require('path');

const prismaDir = path.join(__dirname, '..', 'prisma');
const baseFile = path.join(prismaDir, 'base-models.prisma');
const outputFile = path.join(prismaDir, 'schema.prisma');

const header = `// =========================================================================
// THIS FILE IS AUTO-GENERATED BY scripts/generate-schema.js
// DO NOT EDIT DIRECTLY.
// Edit base-models.prisma and run \`node scripts/generate-schema.js\`
// =========================================================================

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  schemas  = ["auth", "aquasphere", "badana"]
}

// ==========================================
// AUTH SCHEMA
// ==========================================

model User {
  id           String   @id @default(uuid())
  email        String   @unique
  passwordHash String
  role         Role
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt

  @@schema("auth")
}

enum Role {
  OWNER
  ADMIN
  PRODUCTION_MANAGER
  ACCOUNTANT
  MARKETING_MANAGER

  @@schema("auth")
}

`;

function generateSchema() {
  const baseContent = fs.readFileSync(baseFile, 'utf8');

  // Aquasphere
  const aquasphereContent = baseContent
    .replace(/\[\[PREFIX\]\]/g, 'Aquasphere')
    .replace(/\[\[SCHEMA\]\]/g, 'aquasphere');

  // Badana
  const badanaContent = baseContent
    .replace(/\[\[PREFIX\]\]/g, 'Badana')
    .replace(/\[\[SCHEMA\]\]/g, 'badana');

  const fullSchema = [
    header,
    '// ==========================================\n// AQUASPHERE SCHEMA\n// ==========================================\n',
    aquasphereContent,
    '\n// ==========================================\n// BADANA SCHEMA\n// ==========================================\n',
    badanaContent
  ].join('\n');

  fs.writeFileSync(outputFile, fullSchema, 'utf8');
  console.log('Successfully generated prisma/schema.prisma');
}

generateSchema();
