import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const prismaDir = path.join(__dirname, '..', 'prisma');
const aquasphereFile = path.join(prismaDir, 'aquasphere-models.prisma');
const wadaanaFile = path.join(prismaDir, 'wadaana-models.prisma');
const outputFile = path.join(prismaDir, 'schema.prisma');

const header = `// =========================================================================
// THIS FILE IS AUTO-GENERATED BY scripts/generate-schema.js
// DO NOT EDIT DIRECTLY.
// Edit aquasphere-models.prisma and wadaana-models.prisma, then run \`npm run db:generate-schema\`
// =========================================================================

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  schemas  = ["aquasphere", "wadaana"]
}
`;

function generateSchema() {
  const aquasphereContent = fs.readFileSync(aquasphereFile, 'utf8');
  const wadaanaContent = fs.readFileSync(wadaanaFile, 'utf8');

  const fullSchema = [
    header,
    '// ==========================================\n// AQUASPHERE SCHEMA\n// ==========================================\n',
    aquasphereContent,
    '\n// ==========================================\n// WADAANA SCHEMA\n// ==========================================\n',
    wadaanaContent
  ].join('\n');

  fs.writeFileSync(outputFile, fullSchema, 'utf8');
  console.log('Successfully generated prisma/schema.prisma');
}

generateSchema();
