import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const prismaDir = path.join(__dirname, '..', 'prisma');
const baseFile = path.join(prismaDir, 'base-models.prisma');
const outputFile = path.join(prismaDir, 'schema.prisma');

const header = `// =========================================================================
// THIS FILE IS AUTO-GENERATED BY scripts/generate-schema.js
// DO NOT EDIT DIRECTLY.
// Edit base-models.prisma, then run \`npm run db:generate-schema\`
// =========================================================================

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  schemas  = ["aquasphere", "wadaana"]
}
`;

function generateSchema() {
  const baseContent = fs.readFileSync(baseFile, 'utf8');

  const aquasphereContent = baseContent
    .replace(/__Prefix__/g, 'Aquasphere')
    .replace(/__schema__/g, 'aquasphere');

  const wadaanaContent = baseContent
    .replace(/__Prefix__/g, 'Wadaana')
    .replace(/__schema__/g, 'wadaana');

  const fullSchema = [
    header,
    '// ==========================================\n// AQUASPHERE SCHEMA\n// ==========================================\n',
    aquasphereContent,
    '\n// ==========================================\n// WADAANA SCHEMA\n// ==========================================\n',
    wadaanaContent
  ].join('\n');

  fs.writeFileSync(outputFile, fullSchema, 'utf8');
  console.log('Successfully generated prisma/schema.prisma from base-models.prisma');
}

generateSchema();
